### ISSUE TITLE
Question: Why doesn't Close() close the stream?

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p-core#9] opened 2019-05-27 15:52 UTC
I don't understand this bit of the API. When we are handling Closer interfaces, we close them when we are done using the resource. However, this Closer doesn't actually close the stream. It seems we have to call `Reset` which actually sends an error to the peer. 

https://github.com/libp2p/go-libp2p-core/blob/bac72eb843fa92e49232683ee97d64d30b4e3df9/mux/mux.go#L22-L24

We have had some pain with this when trying the following logic:
- Send a message to the peer
- Close the connection because we don't care about the response or if they received it. 

For the second step, if we call `Reset` then the peer will receive the error only and does not process the message. However, if we call `Close` and the peer doesn't then we have this dangling connection that we don't care about.

**Comment by Stebalien** [comment] 2019-05-27 16:41
So, `Close` currently closes the _write_ half. To close the read half, you need to read the EOF off the stream.

This is clearly not a very nice API and was a terrible mistake. I planned to address this once we merged the go-libp2p-core refractor and now we have.

**Comment by marten-seemann** [comment] 2019-05-27 16:54
> This is clearly not a very nice API and was a terrible mistake. I planned to address this once we merged the go-libp2p-core refractor and now we have.

I don't think this is a mistake. By the way, this exactly how things work for QUIC streams as well. And for TCP connections, if I remember correctly.

**Comment by Stebalien** [comment] 2019-05-27 17:07
The issue is at the API layer, not the protocol layer. That is, users expect `Close()` to close in both directions and free resources. This is what `tcpconn.Close()` does. It's also what a `close(sock)` does in C.

We need to _support_ closing for reading/writing, but we should do the thing users expect by default.

**Comment by aschmahmann** [comment] 2020-06-26 18:05
@raulk I see you're the author on the latest version of the PR for this #155. What's the latest state?

**Closed** 2020-09-02 00:29 UTC
